/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

import ejerciciodevlights.principal;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class pantallaPrincipal extends javax.swing.JFrame {
    public int cantidad;
    public int contador;
    /**
     * Creates new form principal
     */
    public pantallaPrincipal() {
        initComponents();
        
        /*valores de la ventana*/
        setSize(370,400);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Programa DevLigths");
        
        jTxt_string.setVisible(false);
        jBtn_calcular.setVisible(false);
        jTxt_resultado.setVisible(false);
        string_contador.setVisible(false);
        jLabel_ingreseString.setVisible(false);
        jLabel_resultado.setVisible(false);
        jLabel_END.setVisible(false);
        salir.setVisible(false);
        reiniciar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt_string = new javax.swing.JTextField();
        label_cantidadS = new javax.swing.JLabel();
        jBtn_start = new javax.swing.JButton();
        jBtn_calcular = new javax.swing.JButton();
        string_contador = new javax.swing.JLabel();
        jLabel_ingreseString = new javax.swing.JLabel();
        jLabel_resultado = new javax.swing.JTextField();
        jTxt_resultado = new javax.swing.JTextField();
        jLabel_END = new javax.swing.JLabel();
        jBox_cantidad = new javax.swing.JComboBox<>();
        logo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 100));
        setMaximumSize(new java.awt.Dimension(370, 320));
        setMinimumSize(new java.awt.Dimension(370, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxt_string.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_string.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_stringActionPerformed(evt);
            }
        });
        jTxt_string.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_stringKeyTyped(evt);
            }
        });
        getContentPane().add(jTxt_string, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, 346, 30));

        label_cantidadS.setText("Cantidad de string:");
        getContentPane().add(label_cantidadS, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jBtn_start.setText("Comenzar");
        jBtn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_startMouseClicked(evt);
            }
        });
        jBtn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_startActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 11, 166, -1));

        jBtn_calcular.setText("Calcular");
        jBtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, 346, -1));

        string_contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        string_contador.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(string_contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 346, 17));

        jLabel_ingreseString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ingreseString.setText("Ingrese un string");
        getContentPane().add(jLabel_ingreseString, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, 346, -1));

        jLabel_resultado.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_resultado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_resultado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jLabel_resultado.setText("String:");
        jLabel_resultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel_resultadoKeyTyped(evt);
            }
        });
        getContentPane().add(jLabel_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 174, 346, 30));

        jTxt_resultado.setBackground(new java.awt.Color(0, 0, 0));
        jTxt_resultado.setForeground(new java.awt.Color(255, 255, 255));
        jTxt_resultado.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxt_resultado.setText("Resultado:");
        jTxt_resultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_resultadoKeyTyped(evt);
            }
        });
        getContentPane().add(jTxt_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, 346, 30));

        jLabel_END.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_END.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_END.setText("FIN DE PROGRAMA");
        getContentPane().add(jLabel_END, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 346, 30));

        jBox_cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jBox_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 12, -1, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logonuevo3.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 370, 240));

        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        reiniciar.setText("REINICIAR");
        reiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reiniciarMouseClicked(evt);
            }
        });
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        reiniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reiniciarKeyPressed(evt);
            }
        });
        getContentPane().add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_stringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_stringKeyTyped
        /*esta linea evita que se ingresen otros caracteres*/
        char c = evt.getKeyChar(); if (c<'a'||c>'z') evt.consume();
        /*aca limitamos el ingreso de caracteres (s<=100000)*/
        String s = jTxt_string.getText();
        if (s.length() == 100000){ evt.consume();}
        
        
    }//GEN-LAST:event_jTxt_stringKeyTyped

    private void jBtn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_startMouseClicked
        
        /* String cantidadS;*/
        /* cantidad = Integer.parseInt(cantidadS);*/
        
        /*[este es el valor t (entre 1 y 10)]*/
        cantidad = (this.jBox_cantidad.getSelectedIndex())+1;
       
        /*modificaciones en la pantalla*/
        jBtn_start.setVisible(false);
        jBox_cantidad.setVisible(false);
        label_cantidadS.setVisible(false);
        logo.setVisible(false);
        jTxt_string.setVisible(true);
        jBtn_calcular.setVisible(true);
        jTxt_resultado.setVisible(true);
        string_contador.setVisible(true);
        jLabel_ingreseString.setVisible(true);
        jLabel_resultado.setVisible(true);
        
       
        string_contador.setText("Iteraciones restantes: " + cantidad);

    }//GEN-LAST:event_jBtn_startMouseClicked

    private void jBtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_calcularActionPerformed
    
        
        String string;
        string = this.jTxt_string.getText(); /*string a evaluar*/
        int longitud = string.length();
        
        /*controlamos que haya al menos un caracter en el string (s>=1)*/
        if (longitud==0){
            JOptionPane.showMessageDialog(null, "Debe ingresar al menos un caracter."
                    + "","ERROR",JOptionPane.ERROR_MESSAGE);
            cantidad = cantidad +1;
        }
        
        cantidad = cantidad -1;
        int valor = principal.obtenerValor(string);
        this.jTxt_resultado.setText("Similaridad: " + valor);
        this.jTxt_string.setText("");
        this.jLabel_resultado.setText("String: " + string);
        string_contador.setText("Iteraciones restantes: " + cantidad);
        
        if (cantidad == 0){
               jTxt_string.setVisible(false);
               jBtn_calcular.setVisible(false);
               jTxt_resultado.setVisible(false);
               string_contador.setVisible(false);
               jLabel_ingreseString.setVisible(false);
               jLabel_resultado.setVisible(true);
               jTxt_resultado.setVisible(true);
               jLabel_END.setVisible(true);
               logo.setVisible(true);
               salir.setVisible(true);
               reiniciar.setVisible(true);
               this.jTxt_resultado.setText("Resultado: " + valor);
               
               JOptionPane.showMessageDialog(null, "Se evaluo el ultimo String, "
               + "vuelva a iniciar","Informacion",JOptionPane.INFORMATION_MESSAGE);
               
               
        }

    
    }//GEN-LAST:event_jBtn_calcularActionPerformed

    private void jBtn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_startActionPerformed
       /* String cantidadS;  este seria el valor t (entre 1 y 10)*/
        cantidad = (this.jBox_cantidad.getSelectedIndex())+1;
        /* cantidad = Integer.parseInt(cantidadS);*/
        
        
    }//GEN-LAST:event_jBtn_startActionPerformed

    private void jTxt_stringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_stringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_stringActionPerformed

    private void jLabel_resultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel_resultadoKeyTyped
        evt.consume();
    }//GEN-LAST:event_jLabel_resultadoKeyTyped

    private void jTxt_resultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_resultadoKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTxt_resultadoKeyTyped

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reiniciarActionPerformed

    private void reiniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reiniciarKeyPressed

    }//GEN-LAST:event_reiniciarKeyPressed

    private void reiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarMouseClicked
        dispose();
        pantallaPrincipal pantalla = new pantallaPrincipal();
        pantalla.setVisible(true);
    }//GEN-LAST:event_reiniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBox_cantidad;
    private javax.swing.JButton jBtn_calcular;
    private javax.swing.JButton jBtn_start;
    private javax.swing.JLabel jLabel_END;
    private javax.swing.JLabel jLabel_ingreseString;
    private javax.swing.JTextField jLabel_resultado;
    private javax.swing.JTextField jTxt_resultado;
    private javax.swing.JTextField jTxt_string;
    private javax.swing.JLabel label_cantidadS;
    private javax.swing.JLabel logo;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton salir;
    private javax.swing.JLabel string_contador;
    // End of variables declaration//GEN-END:variables
}
