/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

import ejerciciodevlights.principal;

/**
 *
 * @author erick
 */
public class pantallaPrincipal extends javax.swing.JFrame {
    public int cantidad;
    public int contador;
    /**
     * Creates new form principal
     */
    public pantallaPrincipal() {
        initComponents();
        jTxt_string.setVisible(false);
        jBtn_calcular.setVisible(false);
        jTxt_resultado.setVisible(false);
        string_contador.setVisible(false);
        jLabel_ingreseString.setVisible(false);
        jLabel_resultado.setVisible(false);
        jLabel_END.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt_string = new javax.swing.JTextField();
        label_cantidadS = new javax.swing.JLabel();
        jBtn_start = new javax.swing.JButton();
        jBtn_calcular = new javax.swing.JButton();
        string_contador = new javax.swing.JLabel();
        jLabel_ingreseString = new javax.swing.JLabel();
        jLabel_resultado = new javax.swing.JTextField();
        jTxt_resultado = new javax.swing.JTextField();
        jLabel_END = new javax.swing.JLabel();
        jBox_cantidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 100));
        setMaximumSize(new java.awt.Dimension(370, 320));
        setMinimumSize(new java.awt.Dimension(370, 320));

        jTxt_string.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_string.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_stringActionPerformed(evt);
            }
        });
        jTxt_string.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_stringKeyTyped(evt);
            }
        });

        label_cantidadS.setText("Cantidad de string:");

        jBtn_start.setText("Comenzar");
        jBtn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_startMouseClicked(evt);
            }
        });
        jBtn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_startActionPerformed(evt);
            }
        });

        jBtn_calcular.setText("Calcular Similaridad");
        jBtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_calcularActionPerformed(evt);
            }
        });

        string_contador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_ingreseString.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ingreseString.setText("Ingrese un string");

        jLabel_resultado.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_resultado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabel_resultado.setText("String:");

        jTxt_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_resultado.setText("Resultado:");

        jLabel_END.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_END.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_END.setText("FIN DE PROGRAMA");

        jBox_cantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_END, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxt_resultado)
                    .addComponent(jTxt_string, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(string_contador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_cantidadS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBox_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_ingreseString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtn_calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_resultado, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cantidadS)
                    .addComponent(jBtn_start)
                    .addComponent(jBox_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_END, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ingreseString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_string, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(string_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_stringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_stringKeyTyped
        char c = evt.getKeyChar(); if (c<'a'||c>'z') evt.consume();
        String s = jTxt_string.getText();
        if (s.length() == 100000){ evt.consume();}
    }//GEN-LAST:event_jTxt_stringKeyTyped

    private void jBtn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_startMouseClicked
        
        /* String cantidadS;  este seria el valor t (entre 1 y 10)*/
        cantidad = (this.jBox_cantidad.getSelectedIndex())+1;
        /* cantidad = Integer.parseInt(cantidadS);
        
        /*restriccion de cantidad de iteraciones*/
        if ( (cantidad < 1) || ( cantidad > 10 ) ){
            
        }
       
        jBtn_start.setVisible(false);
        jBox_cantidad.setVisible(false);
        label_cantidadS.setVisible(false);
        jTxt_string.setVisible(true);
        jBtn_calcular.setVisible(true);
        jTxt_resultado.setVisible(true);
        string_contador.setVisible(true);
        jLabel_ingreseString.setVisible(true);
        jLabel_resultado.disable();
        jLabel_resultado.setVisible(true);
        jTxt_resultado.disable();
       
        string_contador.setText("Iteraciones restantes: " + cantidad);

    }//GEN-LAST:event_jBtn_startMouseClicked

    private void jBtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_calcularActionPerformed
    
        
        String string;
        string = this.jTxt_string.getText(); /*string a evaluar*/
        int longitud = string.length();
        
        /*restriccion de longitud del string*/
        if ( (longitud > 100000) || (longitud < 1) ){
            
        }
        
        cantidad = cantidad -1;
        int valor = principal.obtenerValor(string);
        this.jTxt_resultado.setText("Similaridad: " + valor);
        this.jTxt_string.setText("");
        this.jLabel_resultado.setText("String: " + string);
        string_contador.setText("Iteraciones restantes: " + cantidad);
        
        if (cantidad == 0){
               jTxt_string.setVisible(false);
               jBtn_calcular.setVisible(false);
               jTxt_resultado.setVisible(false);
               string_contador.setVisible(false);
               jLabel_ingreseString.setVisible(false);
               jLabel_resultado.setVisible(true);
               jTxt_resultado.setVisible(true);
               jLabel_END.setVisible(true);
               this.jTxt_resultado.setText("Resultado: " + valor);
               
               
        }

    
    }//GEN-LAST:event_jBtn_calcularActionPerformed

    private void jBtn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_startActionPerformed
       /* String cantidadS;  este seria el valor t (entre 1 y 10)*/
        cantidad = (this.jBox_cantidad.getSelectedIndex())+1;
        /* cantidad = Integer.parseInt(cantidadS);*/
        
        
    }//GEN-LAST:event_jBtn_startActionPerformed

    private void jTxt_stringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_stringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_stringActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBox_cantidad;
    private javax.swing.JButton jBtn_calcular;
    private javax.swing.JButton jBtn_start;
    private javax.swing.JLabel jLabel_END;
    private javax.swing.JLabel jLabel_ingreseString;
    private javax.swing.JTextField jLabel_resultado;
    private javax.swing.JTextField jTxt_resultado;
    private javax.swing.JTextField jTxt_string;
    private javax.swing.JLabel label_cantidadS;
    private javax.swing.JLabel string_contador;
    // End of variables declaration//GEN-END:variables
}
