/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantalla;

/**
 *
 * @author erick
 */
public class principal extends javax.swing.JFrame {
    public int cantidad;
    public int contador;
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        jTxt_string.setVisible(false);
        jBtn_calcular.setVisible(false);
        jTxt_resultado.setVisible(false);
        string_contador.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxt_string = new javax.swing.JTextField();
        label_cantidadS = new javax.swing.JLabel();
        jTxt_cantidad = new javax.swing.JTextField();
        jBtn_start = new javax.swing.JButton();
        jBtn_calcular = new javax.swing.JButton();
        jTxt_resultado = new javax.swing.JTextField();
        string_contador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxt_string.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_string.setText("Ingresar String");
        jTxt_string.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_stringKeyTyped(evt);
            }
        });

        label_cantidadS.setText("Cantidad de string (1-10):");

        jTxt_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTxt_cantidad.setSelectionEnd(10);
        jTxt_cantidad.setSelectionStart(1);
        jTxt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_cantidadActionPerformed(evt);
            }
        });
        jTxt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxt_cantidadKeyTyped(evt);
            }
        });

        jBtn_start.setText("Comenzar");
        jBtn_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn_startMouseClicked(evt);
            }
        });

        jBtn_calcular.setText("Calcular Similaridad");
        jBtn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_calcularActionPerformed(evt);
            }
        });

        jTxt_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxt_resultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(string_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_string, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_cantidadS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jBtn_calcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxt_resultado, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cantidadS)
                    .addComponent(jTxt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_start))
                .addGap(18, 18, 18)
                .addComponent(jTxt_string, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtn_calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(string_contador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_stringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_stringKeyTyped
        char c = evt.getKeyChar(); if (c<'a'||c>'z') evt.consume();
    }//GEN-LAST:event_jTxt_stringKeyTyped

    private void jBtn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn_startMouseClicked
        jBtn_start.setVisible(false);
        jTxt_cantidad.setVisible(false);
        label_cantidadS.setVisible(false);
        jTxt_string.setVisible(true);
        jBtn_calcular.setVisible(true);
        jTxt_resultado.setVisible(true);
        string_contador.setVisible(true);
        
        String cantidadS;
        cantidadS = this.jTxt_cantidad.getText();
        cantidad = Integer.parseInt(cantidadS);

    }//GEN-LAST:event_jBtn_startMouseClicked

    private void jBtn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_calcularActionPerformed
    int i = 0;
    while (cantidad > i){

        String string;
        string = this.jTxt_string.getText();

        this.jTxt_resultado.setText(string);
        this.jTxt_string.setText("");

        this.string_contador.setText("String: " + i);
        i = i+1;
    }
    
    }//GEN-LAST:event_jBtn_calcularActionPerformed

    private void jTxt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_cantidadActionPerformed
    
    }//GEN-LAST:event_jTxt_cantidadActionPerformed

    private void jTxt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_cantidadKeyTyped
        char c = evt.getKeyChar(); if (c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_jTxt_cantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_calcular;
    private javax.swing.JButton jBtn_start;
    private javax.swing.JTextField jTxt_cantidad;
    private javax.swing.JTextField jTxt_resultado;
    private javax.swing.JTextField jTxt_string;
    private javax.swing.JLabel label_cantidadS;
    private javax.swing.JLabel string_contador;
    // End of variables declaration//GEN-END:variables
}
